Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2020-11, with the labels that each got.

#71 UB GPUArrays to 5.0/5.1
  Project.toml
Labels: arrays, bug

#55 Accept hooks for user-defined globals
  Manifest.toml
  docs/src/globals.md
  src/device/gcn/hostcall.jl
  src/execution.jl
  test/device/globals.jl
  test/hsa/global.jl
  test/runtests.jl
Labels: enhancement

#72 rocRAND
  Project.toml
  gen/rocm-external/patches/rocrand_common.patch
  gen/rocm-external/wrap.jl
  src/AMDGPU.jl
  src/array.jl
  src/rand/error.jl
  src/rand/librocrand.jl
  src/rand/librocrand_common.jl
  src/rand/random.jl
  src/rand/rocRAND.jl
  src/random.jl
  test/rocarray/fft.jl
  test/rocarray/random.jl
  test/runtests.jl
  test/util.jl
Labels: arrays, enhancement
