Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2021-02, with the labels that each got.

#94 Look for libhsa-runtime64.so.1
  deps/build.jl
  docs/src/index.md
  docs/src/quickstart.md
  src/AMDGPU.jl
  src/hsa/HSA.jl
  src/hsa/libhsa_api.jl
Labels: bug, debugging

#98 Silence queue destroy finalizer errors
  src/queue.jl
Labels: ci, hsa, tests

#101 Fix kernel argument alignment
  src/kernel.jl
  src/queue.jl
  test/device/launch.jl
Labels: bug

#102 Fix alloc_local
  src/device/gcn/memory_static.jl
  test/device/memory.jl
Labels: bug

#105 Added support for HSA artifacts
  Manifest.toml
  Project.toml
  deps/build.jl
  deps/loaddeps.jl
Labels: enhancement, hsa

#104 Add mapreducedim!
  src/AMDGPU.jl
  src/agent.jl
  src/array.jl
  src/broadcast.jl
  src/device/gcn/indexing.jl
  src/hsa/libhsa_api.jl
  src/mapreduce.jl
  src/runtime.jl
  test/hsa/agent.jl
  test/runtests.jl
Labels: arrays, enhancement

#107 Update to GPUCompiler 0.10
  Manifest.toml
  Project.toml
  src/compiler.jl
  src/device/runtime.jl
  src/execution.jl
  src/execution_utils.jl
  src/reflection.jl
Labels: upstream

#108 Fix CompatHelper config
  .github/workflows/CompatHelper.yml
Labels: ci
