Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2021-11, with the labels that each got.

#180 Make build failure logging more verbose
  deps/build.jl
  deps/loaddeps.jl
  src/AMDGPU.jl
  src/device/runtime.jl
  src/utils.jl
Labels: bug, ci

#182 Test multiple GPUArrays versions
  .buildkite/pipeline.yml
  Manifest.toml.gpuarrays-6
  Manifest.toml.gpuarrays-7
  src/array.jl
  src/compat.jl
Labels: ci

#176 rocprintf: Avoid reading bad data
  src/device/gcn/output.jl
  test/pointer.jl
  test/runtests.jl
Labels: bug, needs tests, output

#174 Add errorhandler for async queue errors
  src/AMDGPU.jl
  src/kernel.jl
  src/queue.jl
  src/runtime.jl
  src/signal.jl
  src/statussignal.jl
  test/hsa/error.jl
Labels: enhancement, hsa, needs tests

#167 at-roc: Support threads and blocks kwargs
  src/execution.jl
  test/device/launch.jl
Labels: enhancement

#181 bump GPUCompiler to 0.13
  Manifest.toml
  Project.toml
Labels: enhancement, upstream
