Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2022-10, with the labels that each got.

#307 Update bindeps search path
  deps/bindeps.jl
Labels: bug, deps

#310 Prioritise ENV var to use or not artifacts
  src/AMDGPU.jl
Labels: bug, deps

#311 Add dynamic local memory support
  .gitignore
  docs/src/memory.md
  src/compiler.jl
  src/highlevel.jl
  src/kernel.jl
  test/device/memory.jl
Labels: enhancement, codegen

#316 random: Load definitions without rocRAND
  src/AMDGPU.jl
Labels: bug, rng
