Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2022-11, with the labels that each got.

#324 Fix double unsafe_free calls
  src/array.jl
  src/device/gcn/hostcall.jl
  src/runtime/memory.jl
  test/rocarray/base.jl
Labels: bug, enhancement, arrays

#320 Add MIOpen
  .buildkite/pipeline.yml
  .gitignore
  Manifest.toml
  Manifest.toml.gpuarrays-7
  contrib/manifest-commands.jl
  deps/bindeps.jl
  docs/src/index.md
  gen/Manifest.toml
  gen/Project.toml
  gen/miopen/generator.jl
  gen/miopen/miopen-generator.toml
  src/AMDGPU.jl
  src/dnn/MIOpen.jl
  src/dnn/convolution.jl
  src/dnn/descriptors.jl
  src/dnn/low_level.jl
  src/utils.jl
  test/Project.toml
  test/dnn/miopen.jl
  test/runtests.jl
  test/setup.jl
Labels: enhancement, arrays, neural networks

#328 Cast to Ptr before checking NULL pointer
  src/runtime/executable.jl
Labels: bug, codegen

#333 Resize! support
  src/array.jl
  test/rocarray/base.jl
Labels: enhancement, arrays, needs tests
