Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2022-07, with the labels that each got.

#248 LB GPUCompiler to 0.16.2
  Manifest.toml
  Manifest.toml.gpuarrays-6
  Manifest.toml.gpuarrays-7
  Project.toml
  contrib/manifest-commands.jl
Labels: upstream

#246 Add BackToCPU struct to reduce 'view' allocations
  src/array.jl
Labels: arrays, performance

#250 launch: Fix groupsize dimension check
  src/device/gcn/indexing.jl
  src/launch.jl
  test/device/launch.jl
Labels: bug, launch

#249 Optimize kernel setup and launch
  .buildkite/pipeline.yml
  deps/loaddeps.jl
  src/AMDGPU.jl
  src/compiler.jl
  src/device.jl
  src/device/array.jl
  src/device/gcn/hostcall.jl
  src/highlevel.jl
  src/kernel-signal.jl
  src/kernel.jl
  src/launch.jl
  src/memory.jl
  src/thread-utils.jl
  test/device/hostcall.jl
Labels: performance, needs tests

#257 CI: Switch GHA to 1.7 release
  .github/workflows/ci-julia-1.7.yml
Labels: ci

#253 device: Add device_id method
  src/highlevel.jl
  test/hsa/device.jl
Labels: hsa

#254 Re-export indexing intrinsics
  docs/src/api.md
  docs/src/quickstart.md
  src/AMDGPU.jl
  src/array.jl
  src/deprecations.jl
  src/device/gcn/indexing.jl
  src/device/gcn/synchronization.jl
  src/mapreduce.jl
  test/codegen/synchronization.jl
  test/device/indexing.jl
  test/device/output.jl
  test/device/vadd.jl
  test/device/wavefront.jl
Labels: intrinsics

#258 queue: Allow setting priority from ctor
  docs/src/queues_signals.md
  src/queue.jl
  test/hsa/queue.jl
  test/runtests.jl
Labels: hsa, performance

#259 math: Make signbit return Bool
  src/device/gcn/math.jl
  test/device/math.jl
Labels: bug, intrinsics
