Repository JuliaGPU/AMDGPU.jl, pull requests merged in 2023-01, with the labels that each got.

#349 Add GPUCompiler 0.17 to compat
  Project.toml
Labels: upstream

#348 Add local memory allocation helpers
  docs/src/memory.md
  src/AMDGPU.jl
  src/array.jl
  src/compiler.jl
  src/device/gcn/memory_static.jl
  test/device/memory.jl
Labels: enhancement, arrays, codegen

#353 Fix `unsafe_free!` not actually freeing
  src/array.jl
  src/runtime/error.jl
  src/runtime/kernel-signal.jl
  src/runtime/memory.jl
  src/runtime/signal.jl
  src/runtime/sync.jl
  test/rocarray/base.jl
Labels: bug, arrays, hsa

#359 tests: Properly unwrap Distributed exceptions
  test/runtests.jl
Labels: bug, tests

#263 Add timespan logging via TimespanLogging.jl
  .buildkite/pipeline.yml
  Project.toml
  docs/make.jl
  docs/src/logging.md
  src/AMDGPU.jl
  src/compiler.jl
  src/runtime/device.jl
  src/runtime/kernel-signal.jl
  src/runtime/kernel.jl
  src/runtime/launch.jl
  src/runtime/logging.jl
  src/runtime/memory.jl
  src/runtime/queue.jl
  src/runtime/signal.jl
  test/logging.jl
  test/runtests.jl
Labels: logging

#361 Reduce signal wait allocations
  src/runtime/signal.jl
Labels: bug, performance

#362 Add more intrinsics, enable `always_inline`
  src/AMDGPU.jl
  src/compiler/codegen.jl
  src/compiler/device-libs.jl
  src/compiler/global-hooks.jl
  src/compiler/utils.jl
  src/device/gcn/atomics.jl
  src/device/gcn/execution_control.jl
  src/device/gcn/hostcall.jl
  src/device/gcn/hostcall_signal_helpers.jl
  src/device/gcn/output.jl
  src/runtime/memory.jl
  test/device/execution_control.jl
  test/device/globals.jl
Labels: bug, enhancement, performance, codegen, hostcall, output

#364 Implement unified getinfo interface
  .buildkite/pipeline.yml
  src/AMDGPU.jl
  src/highlevel.jl
  src/mapreduce.jl
  src/random.jl
  src/runtime/device.jl
  src/runtime/executable.jl
  src/runtime/kernel.jl
  src/runtime/queue.jl
  src/utils.jl
  test/device/output.jl
  test/device/wavefront.jl
  test/hsa/getinfo.jl
  test/runtests.jl
Labels: enhancement

#363 Simplify math intrinsics
  src/device/gcn/math.jl
  src/device/gcn/wavefront.jl
  test/device/math.jl
  test/device/wavefront.jl
  test/external/forwarddiff.jl
Labels: enhancement, performance, intrinsics

#326 Add occupancy API and groupsize tuning
  Project.toml
  docs/make.jl
  docs/src/kernel_launch.md
  docs/src/memory.md
  src/AMDGPU.jl
  src/compiler/codegen.jl
  src/compiler/occupancy.jl
  src/highlevel.jl
  src/runtime/execution.jl
  src/runtime/kernel.jl
  test/device/launch.jl
Labels: enhancement, performance, codegen

#366 Add memory allocation limiters
  src/runtime/kernel.jl
  src/runtime/memory.jl
Labels: enhancement, launch
